# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ntonconversion import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """
        Sets up all the Widgets inside the Main Window and hooks their events to them.
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 597)

        self.buttons = []

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 200, 771, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_DEL = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_DEL.setObjectName("button_DEL")
        self.gridLayout.addWidget(self.button_DEL, 4, 3, 1, 1)
        self.button_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setCheckable(False)
        self.button_1.setFlat(False)
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 0, 0, 1, 1)
        self.button_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 0, 1, 1, 1)
        self.button_D = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_D.setObjectName("button_D")
        self.gridLayout.addWidget(self.button_D, 3, 1, 1, 1)
        self.button_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 1, 3, 1, 1)
        self.button_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 2, 0, 1, 1)
        self.button_A = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_A.setObjectName("button_A")
        self.gridLayout.addWidget(self.button_A, 2, 2, 1, 1)
        self.button_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 1, 2, 1, 1)
        self.button_B = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_B.setObjectName("button_B")
        self.gridLayout.addWidget(self.button_B, 2, 3, 1, 1)
        self.button_F = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_F.setObjectName("button_F")
        self.gridLayout.addWidget(self.button_F, 3, 3, 1, 1)
        self.button_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 1, 0, 1, 1)
        self.button_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 0, 2, 1, 1)
        self.button_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 2, 1, 1, 1)
        self.button_E = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_E.setObjectName("button_E")
        self.gridLayout.addWidget(self.button_E, 3, 2, 1, 1)
        self.button_C = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_C.setObjectName("button_C")
        self.gridLayout.addWidget(self.button_C, 3, 0, 1, 1)
        self.button_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 1, 1, 1, 1)
        self.button_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 0, 3, 1, 1)
        self.convertButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.convertButton.setObjectName("convertButton")
        self.gridLayout.addWidget(self.convertButton, 4, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 771, 186))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputLine = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.outputLine.setFrame(True)
        self.outputLine.setReadOnly(True)
        self.outputLine.setClearButtonEnabled(False)
        self.outputLine.setObjectName("outputLine")
        self.gridLayout_2.addWidget(self.outputLine, 1, 1, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.inputLabel.setObjectName("inputLabel")
        self.gridLayout_2.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.inputN = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.inputN.setMinimum(2)
        self.inputN.setMaximum(16)
        self.inputN.setObjectName("inputN")
        self.inputN.valueChanged.connect(self.activateButtons)
        self.gridLayout_2.addWidget(self.inputN, 0, 3, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_2.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.outputN = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.outputN.setMinimum(2)
        self.outputN.setMaximum(16)
        self.outputN.setValue(10)
        self.outputN.setObjectName("outputN")
        self.gridLayout_2.addWidget(self.outputN, 1, 3, 1, 1)
        self.inputNLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.inputNLabel.setObjectName("inputNLabel")
        self.gridLayout_2.addWidget(self.inputNLabel, 0, 2, 1, 1)
        self.outputNLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.outputNLabel.setObjectName("outputNLabel")
        self.gridLayout_2.addWidget(self.outputNLabel, 1, 2, 1, 1)
        self.inputLine = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.inputLine.setText("")
        self.inputLine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputLine.setReadOnly(True)
        self.inputLine.setObjectName("inputLine")
        self.gridLayout_2.addWidget(self.inputLine, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.addButtons()
        self.connectButtons()
        self.activateButtons()

    def addButtons(self):
        """
        Add all the QPushButton instances to a list for use later on.
        """
        self.buttons.append(self.button_0)
        self.buttons.append(self.button_1)
        self.buttons.append(self.button_2)
        self.buttons.append(self.button_3)
        self.buttons.append(self.button_4)
        self.buttons.append(self.button_5)
        self.buttons.append(self.button_6)
        self.buttons.append(self.button_7)
        self.buttons.append(self.button_8)
        self.buttons.append(self.button_9)
        self.buttons.append(self.button_A)
        self.buttons.append(self.button_B)
        self.buttons.append(self.button_C)
        self.buttons.append(self.button_D)
        self.buttons.append(self.button_E)
        self.buttons.append(self.button_F)

    def connectButtons(self):
        """
        Connect all the buttons to their respective signal methods.
        """

        self.button_0.clicked.connect(lambda: self.add_character_to_input_line(self.button_0))
        self.button_1.clicked.connect(lambda: self.add_character_to_input_line(self.button_1))
        self.button_2.clicked.connect(lambda: self.add_character_to_input_line(self.button_2))
        self.button_3.clicked.connect(lambda: self.add_character_to_input_line(self.button_3))
        self.button_4.clicked.connect(lambda: self.add_character_to_input_line(self.button_4))
        self.button_5.clicked.connect(lambda: self.add_character_to_input_line(self.button_5))
        self.button_6.clicked.connect(lambda: self.add_character_to_input_line(self.button_6))
        self.button_7.clicked.connect(lambda: self.add_character_to_input_line(self.button_7))
        self.button_8.clicked.connect(lambda: self.add_character_to_input_line(self.button_8))
        self.button_9.clicked.connect(lambda: self.add_character_to_input_line(self.button_9))
        self.button_A.clicked.connect(lambda: self.add_character_to_input_line(self.button_A))
        self.button_B.clicked.connect(lambda: self.add_character_to_input_line(self.button_B))
        self.button_C.clicked.connect(lambda: self.add_character_to_input_line(self.button_C))
        self.button_D.clicked.connect(lambda: self.add_character_to_input_line(self.button_D))
        self.button_E.clicked.connect(lambda: self.add_character_to_input_line(self.button_E))
        self.button_F.clicked.connect(lambda: self.add_character_to_input_line(self.button_F))

        self.button_DEL.clicked.connect(self.delete_last_char)
        self.convertButton.clicked.connect(self.convertBases)

    def add_character_to_input_line(self, btn):
        """
        Method that adds numbers to the input line based on the button pressed.
        """
        value = self.inputLine.text()

        self.inputLine.setText(value + btn.text())

    def delete_last_char(self):
        """
        Method that deletes the last inputed character in input line after clicking the DEL button.
        """
        self.inputLine.setText(self.inputLine.text()[:-1])

    def convertBases(self):
        """
        Method triggered when the convert button is clicked by converting the number in input line from the value in
        input spin box to output spin box..
        """
        inputN = int(self.inputN.text())
        outputN = int(self.outputN.text())
        number = self.inputLine.text()

        converted = convertFromNtoN(inputN, outputN, number)

        self.outputLine.setText(converted)

    def activateButtons(self):
        """
        Method triggered when one of the spin boxes value is changed, to enable/disable buttons based on the input base spin box.
        """
        value = int(self.inputN.text())

        for button in self.buttons:

            try:
                button_value = int(button.text())
            except ValueError:
                button_value = conversion_table[button.text()]            

            if value <= button_value:
                button.setEnabled(False)
            else:
                button.setEnabled(True)

    def retranslateUi(self, MainWindow):
        """
        Method that arranges the set inside the QWidget instances.
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_DEL.setText(_translate("MainWindow", "DEL"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_D.setText(_translate("MainWindow", "D"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_A.setText(_translate("MainWindow", "A"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_B.setText(_translate("MainWindow", "B"))
        self.button_F.setText(_translate("MainWindow", "F"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_E.setText(_translate("MainWindow", "E"))
        self.button_C.setText(_translate("MainWindow", "C"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.outputLine.setPlaceholderText(_translate("MainWindow", "Output Number"))
        self.inputLabel.setText(_translate("MainWindow", "Input:"))
        self.outputLabel.setText(_translate("MainWindow", "Output:"))
        self.inputNLabel.setText(_translate("MainWindow", "Input N:"))
        self.outputNLabel.setText(_translate("MainWindow", "Output N:"))
        self.inputLine.setPlaceholderText(_translate("MainWindow", "Input Number"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())